### ISSUE TITLE
callDelegate result is 0 (successful) when it runs Out of Gas

### ISSUE THREAD

**Issue by hugo-dc** [ewasm/hera#129]
callDelegate result is 0 (successful) when it runs Out of Gas.

I created this test case for this: 
https://github.com/hugo-dc/tests/blob/fe9fa523316f00eadb7f4620d7e7376d5532289e/src/GeneralStateTestsFiller/stEWASMTests/utils/callDelegateOOGFiller.yml

**Comment by axic** [comment]
Can you try doing a `revert` within a delegatecall?

**Comment by hugo-dc** [comment]
Same result for `revert`, there is an Internal error while calling `revert` or `result`:

```
InternalError: Out of bounds (destination) memory copy.
```
It is thrown here: https://github.com/ewasm/hera/blob/master/src/eei.cpp#L655

`dst.size() = 0`, `length = 2`

Not sure if this problem is new, or if @lrettig already had this problem when he wrote the `revert` test case: https://github.com/ewasm/tests/blob/wasm-tests/src/GeneralStateTestsFiller/stEWASMTests/utils/revertFiller.yml (I ran this test case and got the same InternalError)

**Comment by lrettig** [comment]
I don't recall seeing this error, let me know if I can help take a look!

**Comment by axic** [comment]
Is this still a problem?

**Comment by hugo-dc** [comment]
It is not throwing the InternalError anymore (InternalError: Out of bounds (destination) memory copy.), but I still receive 0 (success) as a result.

**Comment by hugo-dc** [comment]
Hera is catching the OOG exception correctly, and it is setting status 2 here: https://github.com/ewasm/hera/blob/master/src/hera.cpp#L323 

But, after this line is executed https://github.com/ewasm/hera/blob/master/src/eei.cpp#L644 , i see the status code as 0 (success), i also can see the result is set to success here https://github.com/ethereum/cpp-ethereum/blob/develop/libevm/ExtVMFace.cpp#L227

**Comment by axic** [comment]
@chfast can you have a quick look into this?

**Comment by chfast** [comment]
Can you give me full command to reproduce it?

**Comment by chfast** [comment]
I've found the cause of the problem. Will fix it soon.

**Comment by axic** [comment]
@hugo-dc can you retest with latest cpp-ethereum?

**Comment by hugo-dc** [comment]
I tested with the latest cpp-ethereum, now callDelegate is returning 2, according to the interface definition callDelegate should return 0 on success, 1 on failure and 2 on revert. I'm not sure if it's OK to return 2 or if should return 1.

**Comment by axic** [comment]
It seems it is a limitation/bug in cpp-ethereum: https://github.com/ethereum/cpp-ethereum/blob/develop/libevm/ExtVMFace.cpp#L232

@chfast can we improve this?

**Comment by chfast** [comment]
I think we have 2 options here:
1. Compress the information to SUCCESS / FAILURE only. For that I can change EVM_REVERT to EVM_FAILURE if that helps.
2. Pass the same status code as callee returned. This is much harder to do in cpp-ethereum at the moment, because this information is lost on the way. I plan to finally get to this point, but it requires a lot of refactoring steps.

Quick workaround on Hera side for now would be to only checking for EVM_SUCCESS and status code > 0.

**Comment by axic** [comment]
I think `ExtVMFace` is actually wrong, because `revert` is a subset of `failure`, but currently there is no way to handle all failures, just that very specific subset.

It should be just fixed to return `FAILURE` for the moment.

As a quick hack to support `REVERT`, you could check for `!success && gas_used < startgas`.

**Comment by axic** [comment]
@chfast also the same problem is there in `create`, it can only return `FAILURE`.

**Comment by chfast** [comment]
Just to confirm current status: both create and call should report EVM_STATUS or EVM_FAILURE now.
